import '../styles/globals.css';
import { Toaster } from 'react-hot-toast';
import BottomNav from '@/components/BottomNav';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <BottomNav /> {/* 全ページに表示されるナビゲーションバー */}
        <Toaster />
      </body>
    </html>
  );
}
